# Generated by Django 3.0.3 on 2020-02-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('blood_group', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Patient Registration Details',
            },
        ),
        migrations.DeleteModel(
            name='registrationData',
        ),
    ]
