# Generated by Django 3.0.3 on 2020-02-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0003_auto_20200225_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Doctor_Details',
            },
        ),
        migrations.DeleteModel(
            name='signupformsData',
        ),
    ]
