# Generated by Django 3.0.3 on 2020-02-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0004_auto_20200225_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('haemoglobin', models.CharField(max_length=20)),
                ('wbc', models.CharField(max_length=20)),
                ('granulocyte', models.CharField(max_length=20)),
                ('neutrophils', models.CharField(max_length=20)),
                ('platelet_Count', models.CharField(max_length=20)),
                ('cholestrol', models.CharField(max_length=20)),
                ('triglycerides', models.CharField(max_length=20)),
                ('tsh', models.CharField(max_length=20)),
                ('bilirubin_total', models.CharField(max_length=20)),
                ('globulins', models.CharField(max_length=20)),
                ('blood_urea', models.CharField(max_length=20)),
                ('albumin', models.CharField(max_length=20)),
                ('potassium', models.CharField(max_length=20)),
                ('sodium', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Patient Records',
            },
        ),
    ]
