# Generated by Django 3.0.3 on 2020-03-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0005_patientrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('mobile_number', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Admin Registration Details',
            },
        ),
    ]
