# Generated by Django 3.0.3 on 2020-03-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0006_adminregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorDataa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('disrict', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('employee_id', models.IntegerField()),
                ('specialization', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Doctor_Details',
            },
        ),
        migrations.DeleteModel(
            name='doctorData',
        ),
    ]
