# Generated by Django 3.0.3 on 2020-03-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0007_auto_20200307_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Departments Available',
            },
        ),
    ]
