# Generated by Django 3.0.3 on 2020-03-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0008_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminRegistrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('mobile_number', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Admin Registration Details',
            },
        ),
        migrations.DeleteModel(
            name='adminRegistration',
        ),
    ]
