# Generated by Django 3.0.3 on 2020-03-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0009_auto_20200310_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('mobile_number', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Admin Registration Details',
            },
        ),
        migrations.DeleteModel(
            name='adminRegistrations',
        ),
    ]
