# Generated by Django 3.0.3 on 2020-03-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0010_auto_20200310_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminregistration',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
