# Generated by Django 3.0.3 on 2020-03-10 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0011_auto_20200310_0514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminRegistration',
            new_name='adminRegistrations',
        ),
    ]
