# Generated by Django 3.0.3 on 2020-03-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0013_auto_20200310_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminregistration',
            old_name='time',
            new_name='date',
        ),
    ]
