# Generated by Django 3.0.3 on 2020-03-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0016_auto_20200310_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='settingspage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
                ('fax', models.CharField(max_length=20)),
                ('website_url', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Hospital Settings',
            },
        ),
        migrations.AlterField(
            model_name='adminregistrations',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
