# Generated by Django 3.0.3 on 2020-03-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0018_auto_20200310_0947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctordata',
            old_name='disrict',
            new_name='district',
        ),
    ]
