# Generated by Django 3.0.3 on 2020-03-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0019_auto_20200310_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientRegistrationDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('blood_group', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('mobile_number', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Patient Registration Details',
            },
        ),
        migrations.DeleteModel(
            name='patientRegistrationData',
        ),
    ]
