# Generated by Django 3.0.3 on 2020-03-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0021_appointment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appointment',
            new_name='appointmentpage',
        ),
    ]
