# Generated by Django 3.0.3 on 2020-03-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0022_auto_20200311_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentspage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('appointment_id', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('patient_phone_number', models.IntegerField()),
                ('patient_email', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('appointment_status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Appointment Details',
            },
        ),
        migrations.DeleteModel(
            name='appointmentpage',
        ),
    ]
