# Generated by Django 3.0.3 on 2020-03-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0023_auto_20200311_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=20)),
                ('available_days', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('message', models.TextField()),
                ('schedule_status', models.CharField(max_length=20)),
            ],
        ),
    ]
