# Generated by Django 3.0.3 on 2020-03-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0024_doctorschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='departmentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Departments Available',
            },
        ),
        migrations.DeleteModel(
            name='department',
        ),
    ]
