# Generated by Django 3.0.3 on 2020-03-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0025_auto_20200312_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=20)),
                ('joining_date', models.DateField()),
                ('phone_number', models.IntegerField()),
                ('role', models.TextField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Employees Details',
            },
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'verbose_name_plural': 'Doctors Schedule Details'},
        ),
    ]
