# Generated by Django 3.0.3 on 2020-03-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0031_auto_20200318_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregistrationdatas',
            name='city',
            field=models.TextField(default='tvm'),
        ),
    ]
