# Generated by Django 3.0.4 on 2020-03-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0035_patientregistrationdatas_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='doctor_name',
            field=models.TextField(default='Dr Anitha Samuel'),
        ),
    ]
