# Generated by Django 3.0.4 on 2020-03-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0036_patientrecord_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='username',
            field=models.TextField(default='shivajirm'),
        ),
    ]
