# Generated by Django 3.0.6 on 2020-05-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0037_patientrecord_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregistrationdatas',
            name='insurance',
            field=models.TextField(default='yes'),
        ),
    ]
