# Generated by Django 3.0.6 on 2020-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureHealth', '0040_auto_20200523_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompanylogin',
            name='company_code',
            field=models.CharField(default=112233, max_length=20),
        ),
    ]
